### ISSUE TITLE
Apply --background-color to input regardless of disabled or not

### ISSUE THREAD

**Issue by avdaredevil** [Collaborne/paper-search#9]
Change [these lines](https://github.com/Collaborne/paper-search/blob/master/paper-search-bar.html#L47-L49) to:

``` css
#input {
    background: inherit;
}
```

_**OR Even:**_

``` css
#input[disabled] {
    background: var(--background-color, white);
}
```

Currently I have to hack this behavior by setting non polymeric style to peirce this component and then set it.

Let me know if I am fundamentally missing something about the usage of this component? Thanks!
